export const openNow = "Open now"
export const closedNow = "Closed now, usually opens at "
export const showOnMap = "Show on Map"
export const setLocation = "Set Location"
export const addToLobby = "Add to Lobby"